In [ ]:
import tensorflow as tf
import numpy as np

# Create two large random vectors
vector_size = 10000000  # Size of the vectors
A = np.random.rand(vector_size).astype(np.float32)
B = np.random.rand(vector_size).astype(np.float32)

# Convert to TensorFlow tensors
A_tensor = tf.constant(A)
B_tensor = tf.constant(B)

# Perform vector addition
C_tensor = tf.add(A_tensor, B_tensor)

# Print the result (showing the first 10 elements)
print("Result of A + B (first 10 elements):", C_tensor.numpy()[:10])


Result of A + B (first 10 elements): [0.20970523 1.0159297  0.73858315 1.4044259  0.90752524 0.49566817
 0.7770937  1.0126754  0.73011875 0.82413316]


In [ ]:
!pip install pycuda


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 18.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.9/92.9 kB 7.5 MB/s eta 0:00:00
  Created wheel for pycuda: filename=pycuda-2025.1-cp311-cp311-linux_x86_64.whl size=660425 sha256=76853b2733e971dfcf60d65b577b0769b046fb4581314d1e748c6acca58416ad
  Stored in directory: /root/.cache/pip/wheels/77/7e/6c/d2d1451ea6424cdc3d67b36c16fa7111eafdf2034bc3405666
Successfully built pycuda


In [ ]:
import tensorflow as tf
import numpy as np

# Create random matrices
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.float32)
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.float32)

# Convert to TensorFlow tensors
A_tensor = tf.constant(A)
B_tensor = tf.constant(B)

# Perform matrix multiplication
C_tensor = tf.matmul(A_tensor, B_tensor)

# Print result
print("Result Matrix C (A x B):\n", C_tensor.numpy())


Result Matrix C (A x B):
 [[ 30.  36.  42.]
 [ 66.  81.  96.]
 [102. 126. 150.]]
